// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type DnsGatewayConntrackKey struct {
	_       structs.HostLayout
	PodIp   uint32
	PodPort uint16
	Txid    uint16
}

type DnsGatewayConntrackValue struct {
	_           structs.HostLayout
	CorednsIp   uint32
	Pad         uint32
	TimestampNs uint64
}

type DnsGatewayGatewayConfig struct {
	_              structs.HostLayout
	CorednsIp      uint32
	HostResolverIp uint32
	DnsPort        uint16
	Bypass         uint16
	DefaultAction  uint32
}

type DnsGatewayScratchBuf struct {
	_      structs.HostLayout
	Qname  [128]uint8
	Lookup [128]uint8
}

type DnsGatewaySuffixKey struct {
	_    structs.HostLayout
	Name [128]uint8
}

type DnsGatewaySuffixValue struct {
	_      structs.HostLayout
	Action uint32
	Pad    uint32
}

// LoadDnsGateway returns the embedded CollectionSpec for DnsGateway.
func LoadDnsGateway() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsGatewayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load DnsGateway: %w", err)
	}

	return spec, err
}

// LoadDnsGatewayObjects loads DnsGateway and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DnsGatewayObjects
//	*DnsGatewayPrograms
//	*DnsGatewayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDnsGatewayObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDnsGateway()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DnsGatewaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsGatewaySpecs struct {
	DnsGatewayProgramSpecs
	DnsGatewayMapSpecs
	DnsGatewayVariableSpecs
}

// DnsGatewayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsGatewayProgramSpecs struct {
	DnsGatewayEgress  *ebpf.ProgramSpec `ebpf:"dns_gateway_egress"`
	DnsGatewayIngress *ebpf.ProgramSpec `ebpf:"dns_gateway_ingress"`
}

// DnsGatewayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsGatewayMapSpecs struct {
	ConfigMap    *ebpf.MapSpec `ebpf:"config_map"`
	ConntrackMap *ebpf.MapSpec `ebpf:"conntrack_map"`
	MetricsMap   *ebpf.MapSpec `ebpf:"metrics_map"`
	ScratchMap   *ebpf.MapSpec `ebpf:"scratch_map"`
	SuffixRules  *ebpf.MapSpec `ebpf:"suffix_rules"`
}

// DnsGatewayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsGatewayVariableSpecs struct {
}

// DnsGatewayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDnsGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsGatewayObjects struct {
	DnsGatewayPrograms
	DnsGatewayMaps
	DnsGatewayVariables
}

func (o *DnsGatewayObjects) Close() error {
	return _DnsGatewayClose(
		&o.DnsGatewayPrograms,
		&o.DnsGatewayMaps,
	)
}

// DnsGatewayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDnsGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsGatewayMaps struct {
	ConfigMap    *ebpf.Map `ebpf:"config_map"`
	ConntrackMap *ebpf.Map `ebpf:"conntrack_map"`
	MetricsMap   *ebpf.Map `ebpf:"metrics_map"`
	ScratchMap   *ebpf.Map `ebpf:"scratch_map"`
	SuffixRules  *ebpf.Map `ebpf:"suffix_rules"`
}

func (m *DnsGatewayMaps) Close() error {
	return _DnsGatewayClose(
		m.ConfigMap,
		m.ConntrackMap,
		m.MetricsMap,
		m.ScratchMap,
		m.SuffixRules,
	)
}

// DnsGatewayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDnsGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsGatewayVariables struct {
}

// DnsGatewayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDnsGatewayObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsGatewayPrograms struct {
	DnsGatewayEgress  *ebpf.Program `ebpf:"dns_gateway_egress"`
	DnsGatewayIngress *ebpf.Program `ebpf:"dns_gateway_ingress"`
}

func (p *DnsGatewayPrograms) Close() error {
	return _DnsGatewayClose(
		p.DnsGatewayEgress,
		p.DnsGatewayIngress,
	)
}

func _DnsGatewayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnsgateway_x86_bpfel.o
var _DnsGatewayBytes []byte
